import {
  Activity,
  Award,
  BadgePercent,
  Barcode,
  BriefcaseBusiness,
  Cake,
  Calculator,
  CalendarCheck,
  CalendarDays,
  Code,
  Coins,
  Combine,
  Droplets,
  Eraser,
  FileArchive,
  FileImage,
  FileText,
  Film,
  GraduationCap,
  Grid3x3,
  Hash,
  Heart,
  Image,
  Layers,
  Link2,
  PartyPopper,
  Percent,
  QrCode,
  Ratio,
  RefreshCw,
  School,
  ShieldAlert,
  Sparkles,
  Table2,
  Type,
  UserCheck,
  Wallet,
  Fuel,
  type LucideIcon,
} from "lucide-react";

/**
 * Central registry mapping icon names (stored as plain strings in tool/category
 * data) to the actual lucide-react components. Keeping data files free of JSX
 * lets them stay server-safe and trivially serializable.
 */
export const iconMap: Record<string, LucideIcon> = {
  GraduationCap,
  Activity,
  Percent,
  Type,
  QrCode,
  FileArchive,
  Combine,
  Ratio,
  Layers,
  RefreshCw,
  Wallet,
  Image,
  FileText,
  Calculator,
  Eraser,
  Heart,
  ShieldAlert,
  Cake,
  CalendarDays,
  PartyPopper,
  Award,
  UserCheck,
  School,
  Table2,
  Sparkles,
  CalendarCheck,
  Hash,
  Code,
  Coins,
  Link2,
  Barcode,
  FileImage,
  Film,
  Grid3x3,
  Droplets,
  Fuel,
  BadgePercent,
  BriefcaseBusiness,
};

export function getIcon(name: string): LucideIcon {
  return iconMap[name] ?? Calculator;
}
